# Generated by Django 5.0.7 on 2024-07-23 12:44

import uuid

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Institute",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(editable=False, primary_key=True, serialize=False),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("institute_name", models.CharField(max_length=200)),
                ("institute_reg_number", models.CharField(max_length=100)),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        default="+250784123456",
                        max_length=30,
                        region=None,
                        verbose_name="phone number",
                    ),
                ),
                (
                    "address",
                    models.TextField(default="Enter Address", verbose_name="address"),
                ),
                (
                    "city",
                    models.CharField(default="Nagpur", max_length=180, verbose_name="city"),
                ),
                (
                    "institute_image",
                    models.ImageField(
                        default="/profile_default.png",
                        upload_to="",
                        verbose_name="institute image",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-updated_at"],
                "abstract": False,
            },
        ),
    ]
