# Generated by Django 5.0.7 on 2024-07-24 17:22

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institute',
            name='address',
            field=models.TextField(default='', verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='institute',
            name='institute_reg_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='institute',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(
                default='', max_length=30, region=None, verbose_name='phone number'
            ),
        ),
    ]
