# Generated by Django 5.0.7 on 2024-10-26 19:43

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institutes', '0003_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institute',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(
                default='', max_length=30, region='IN', verbose_name='phone number'
            ),
        ),
    ]
