# Generated by Django 5.0.7 on 2024-11-05 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institutes', '0006_staff'),
    ]

    operations = [
        migrations.DeleteModel(name='Staff',),
    ]
