# Generated by Django 3.2 on 2025-02-26 06:20

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutes', '0009_academicsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicClassSection',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('class_name', models.CharField(max_length=200)),
                ('section_name', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='academicclass',
            name='institute',
        ),
        migrations.RemoveField(
            model_name='academicsection',
            name='institute',
        ),
    ]
