# Generated by Django 3.2 on 2025-02-26 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutes', '0010_auto_20250226_1150'),
        ('students', '0018_auto_20250226_1150'),
        ('attendance', '0004_attendance_academic_class_section'),
    ]

    operations = [
        migrations.DeleteModel(name='AcademicClass',),
        migrations.DeleteModel(name='AcademicSection',),
        migrations.AddField(
            model_name='academicclasssection',
            name='institute',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='class_section', to='institutes.institute'
            ),
        ),
    ]
