# Generated by Django 4.2 on 2025-03-30 19:33

from django.db import migrations, models

import IAS.core_apps.institutes.models


class Migration(migrations.Migration):

    dependencies = [
        ('institutes', '0011_auto_20250226_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institute',
            name='institute_image',
            field=models.ImageField(
                default='/profile_images/default_profile.png',
                upload_to=IAS.core_apps.institutes.models.institute_directory_path,
                verbose_name='institute image'
            ),
        ),
    ]
