# Generated by Django 5.0.7 on 2024-07-23 12:44

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutes', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                (
                    'role_type',
                    models.CharField(
                        choices=[('owner', 'Owner'), ('staff', 'Staff'), ('student', 'Student')], max_length=10
                    )
                ),
                (
                    'institute',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='institute',
                        to='institutes.institute'
                    )
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL
                    )
                ),
            ],
            options={
                'unique_together': {('user', 'institute', 'role_type')},
            },
        ),
    ]
