# Generated by Django 5.0.7 on 2024-10-26 21:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutes', '0004_alter_institute_phone_number'),
        ('users', '0003_alter_role_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['-created_at', '-updated_at']},
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='role',
            name='institute',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='institute_roles', to='institutes.institute'
            ),
        ),
        migrations.AlterField(
            model_name='role',
            name='role_type',
            field=models.CharField(
                choices=[('owner', 'Owner'), ('staff', 'Staff'), ('student', 'Student'), ('anonymous', 'Anonymous')],
                default='staff',
                max_length=10
            ),
        ),
        migrations.AlterField(
            model_name='role',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
