# Generated by Django 5.0.7 on 2024-10-26 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institutes', '0004_alter_institute_phone_number'),
        ('users', '0004_alter_role_options_alter_role_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together={('user', 'institute')},
        ),
    ]
