# Generated by Django 3.2 on 2025-02-09 17:43

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staffs', '0004_staff_about_staff_address_staff_blood_group_and_more'),
        ('students', '0017_delete_attendance'),
        ('institutes', '0009_academicsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('a_date', models.DateField()),
                ('a_in_time', models.TimeField(blank=True, null=True)),
                ('a_out_time', models.TimeField(blank=True, null=True)),
                (
                    'a_status',
                    models.CharField(
                        choices=[('present', 'Present'), ('absent', 'Absent'), ('on leave', 'On Leave'),
                                 ('not marked', 'Not Marked'), ('holiday', 'Holiday'), ('weekend', 'Weekend')],
                        default='not marked',
                        max_length=10
                    )
                ),
                (
                    'a_type',
                    models.CharField(
                        choices=[('owner', 'Owner'), ('staff', 'Staff'), ('student', 'Student'),
                                 ('anonymous', 'Anonymous')],
                        default='student',
                        max_length=10
                    )
                ),
                ('created_by_uuid_role', models.TextField(blank=True, null=True)),
                (
                    'academic_class',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='class_attendance',
                        to='institutes.academicclass'
                    )
                ),
                (
                    'academic_info',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='academic_attendance',
                        to='students.academicinfo'
                    )
                ),
                (
                    'academic_section',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='section_attendance',
                        to='institutes.academicsection'
                    )
                ),
                (
                    'institute',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='institute_attendance',
                        to='institutes.institute'
                    )
                ),
                (
                    'session',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='session_attendance',
                        to='institutes.academicsession'
                    )
                ),
                (
                    'staff',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='staff_attendance', to='staffs.staff'
                    )
                ),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
    ]
