# Generated by Django 3.2 on 2025-02-09 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutes', '0009_academicsession'),
        ('students', '0017_delete_attendance'),
        ('staffs', '0004_staff_about_staff_address_staff_blood_group_and_more'),
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='academic_class',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='class_attendance',
                to='institutes.academicclass'
            ),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='academic_info',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='academic_attendance',
                to='students.academicinfo'
            ),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='academic_section',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='section_attendance',
                to='institutes.academicsection'
            ),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='institute',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='institute_attendance',
                to='institutes.institute'
            ),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='session',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='session_attendance',
                to='institutes.academicsession'
            ),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='staff',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='staff_attendance',
                to='staffs.staff'
            ),
        ),
    ]
