# Generated by Django 3.2 on 2025-02-26 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutes', '0010_auto_20250226_1150'),
        ('attendance', '0003_auto_20250226_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='academic_class_section',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='class_section_attendance',
                to='institutes.academicclasssection'
            ),
        ),
    ]
