# Generated by Django 5.0.7 on 2024-12-09 20:06

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutes', '0009_academicsession'),
        ('students', '0003_student_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicInfo',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                (
                    'academic_class',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='class_academic',
                        to='institutes.academicclass'
                    )
                ),
                (
                    'academic_section',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='section_academic',
                        to='institutes.academicsection'
                    )
                ),
                (
                    'institute',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='institute_academic',
                        to='institutes.institute'
                    )
                ),
                (
                    'session',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='session_academic',
                        to='institutes.academicsession'
                    )
                ),
                (
                    'student',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='student_academic',
                        to='students.student'
                    )
                ),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
    ]
