# Generated by Django 5.0.7 on 2024-12-28 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_academicinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='created_by_uuid_role',
            field=models.TextField(blank=True, null=True),
        ),
    ]
