# Generated by Django 5.0.7 on 2024-12-31 15:07

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutes', '0009_academicsession'),
        ('students', '0005_student_created_by_uuid_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('a_date', models.DateField()),
                ('a_in_time', models.TimeField(blank=True)),
                ('a_out_time', models.TimeField(blank=True, null=True)),
                (
                    'a_status',
                    models.CharField(
                        choices=[('present', 'Present'), ('absent', 'Absent'), ('on leave', 'On Leave'),
                                 ('not marked', 'Not Marked')],
                        default='not marked',
                        max_length=10
                    )
                ),
                ('updated_by_uuid_role', models.TextField(blank=True, null=True)),
                (
                    'academic_class',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='class_attendance',
                        to='institutes.academicclass'
                    )
                ),
                (
                    'academic_info',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='academic_attendance',
                        to='students.academicinfo'
                    )
                ),
                (
                    'academic_section',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='section_attendance',
                        to='institutes.academicsection'
                    )
                ),
                (
                    'institute',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='institute_attendance',
                        to='institutes.institute'
                    )
                ),
                (
                    'session',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='session_attendance',
                        to='institutes.academicsession'
                    )
                ),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
    ]
