# Generated by Django 5.0.7 on 2024-12-31 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='a_in_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='a_status',
            field=models.CharField(
                choices=[('present', 'Present'), ('absent', 'Absent'), ('on leave', 'On Leave'),
                         ('not marked', 'Not Marked'), ('holiday', 'Holiday'), ('weekend', 'Weekend')],
                default='not marked',
                max_length=10
            ),
        ),
    ]
