# Generated by Django 5.0.7 on 2024-12-31 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_alter_attendance_a_in_time_alter_attendance_a_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='created_by_uuid_role',
            field=models.TextField(blank=True, null=True),
        ),
    ]
