# Generated by Django 5.0.7 on 2025-01-02 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_attendance_created_by_uuid_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='updated_by_uuid_role',
        ),
        migrations.AddField(
            model_name='student',
            name='profile_image',
            field=models.ImageField(blank=True, default='/assets/default_profile.png', upload_to=''),
        ),
    ]
