# Generated by Django 5.0.7 on 2025-01-03 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_student_address_student_blood_group_student_dob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='blood_group',
            field=models.CharField(
                blank=True,
                choices=[('A+', 'A+'), ('B+', 'B+'), ('AB+', 'AB+'), ('O+', 'O+'), ('A-', 'A-'), ('B-', 'B-'),
                         ('AB-', 'AB-'), ('O-', 'O-'), ('Other', 'Other')],
                default='Other',
                max_length=10,
                null=True
            ),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(
                blank=True,
                choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('transgender', 'Transgender'),
                         ('prefer not to answer', 'Prefer not to answer')],
                default='prefer not to answer',
                max_length=20,
                null=True
            ),
        ),
    ]
