# Generated by Django 5.0.7 on 2025-01-03 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_alter_student_blood_group_alter_student_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='about',
            field=models.CharField(blank=True, max_length=566, null=True),
        ),
    ]
