# Generated by Django 5.0.7 on 2025-01-03 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_student_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profile_image',
            field=models.ImageField(blank=True, default='/assets/img/default_profile.png', upload_to=''),
        ),
    ]
