# Generated by Django 5.0.7 on 2025-01-03 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_alter_student_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profile_image',
            field=models.ImageField(blank=True, default='/profile_images/default_profile.png', upload_to=''),
        ),
    ]
