# Generated by Django 3.2 on 2025-02-08 12:14

from django.db import migrations, models

import IAS.core_apps.students.models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_alter_student_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='enrollment_number',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='profile_image',
            field=models.ImageField(
                blank=True,
                default='/profile_images/default_profile.png',
                upload_to=IAS.core_apps.students.models.student_directory_path
            ),
        ),
    ]
