# Generated by Django 3.2 on 2025-02-08 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_role_options_alter_role_unique_together'),
        ('students', '0015_auto_20250208_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='role',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, related_name='role_student', to='users.role'
            ),
        ),
    ]
