# Generated by Django 3.2 on 2025-02-26 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutes', '0010_auto_20250226_1150'),
        ('students', '0017_delete_attendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicinfo',
            name='academic_class',
        ),
        migrations.RemoveField(
            model_name='academicinfo',
            name='academic_section',
        ),
        migrations.AddField(
            model_name='academicinfo',
            name='academic_class_section',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='class_section_academic',
                to='institutes.academicclasssection'
            ),
        ),
        migrations.AlterField(
            model_name='academicinfo',
            name='institute',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='institute_academic',
                to='institutes.institute'
            ),
        ),
        migrations.AlterField(
            model_name='academicinfo',
            name='session',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='session_academic',
                to='institutes.academicsession'
            ),
        ),
        migrations.AlterField(
            model_name='academicinfo',
            name='student',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='student_academic',
                to='students.student'
            ),
        ),
    ]
