# Generated by Django 5.0.7 on 2025-01-05 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0003_staff_institute'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='about',
            field=models.CharField(blank=True, max_length=566, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='address',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='blood_group',
            field=models.CharField(
                blank=True,
                choices=[('A+', 'A+'), ('B+', 'B+'), ('AB+', 'AB+'), ('O+', 'O+'), ('A-', 'A-'), ('B-', 'B-'),
                         ('AB-', 'AB-'), ('O-', 'O-'), ('Other', 'Other')],
                default='Other',
                max_length=10,
                null=True
            ),
        ),
        migrations.AddField(
            model_name='staff',
            name='created_by_uuid_role',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='gender',
            field=models.CharField(
                blank=True,
                choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('transgender', 'Transgender'),
                         ('prefer not to answer', 'Prefer not to answer')],
                default='prefer not to answer',
                max_length=20,
                null=True
            ),
        ),
        migrations.AddField(
            model_name='staff',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='profile_image',
            field=models.ImageField(blank=True, default='/profile_images/default_profile.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='staff',
            name='state',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
