# Generated by Django 3.2 on 2025-02-26 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_role_options_alter_role_unique_together'),
        ('staffs', '0004_staff_about_staff_address_staff_blood_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, related_name='role_staff', to='users.role'
            ),
        ),
    ]
